name: Everyday
fileGroups:
  - README.md
options:
  developmentLanguage: ja
  xcodeVersion: 11.5
config:
  Debug: debug
  Release: release
targets:
  Everyday:
    type: application
    platform: iOS
    developmentTarget: 13.0
    sources:
      - path: Everyday
    scheme: {}
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: AV9FQ3YF56
        PRODUCT_BUNDLE_IDENTIFIER: com.tomoki-sun.app.ios.Everyday
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          INFOPLIST_FILE: Everyday/Resources/Info/Debug.plist
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          INFOPLIST_FILE: Everyday/Resources/Info/Release.plist
  EverydayTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: EverydayTests
    dependencies:
      - target: Everyday
    scheme:
      gatherCoverageData: true
      testTargets:
        - EverydayTests
